### ISSUE TITLE
Rename repo and NPM package

### ISSUE THREAD

**Issue by TheKeithStewart** [TheKeithStewart/angular-esri-components#14]
To keep up with best practices for naming conventions of Angular libraries this repo and the NPM package should be renamed.  This will also keep it in line with the `angular-esri-loader` module that was recently changed.

Right now I'm thinking that the new name should be `angular-esri4-components`.  It seems to be that `esri4` still needs to be specified since this package is incompatible with ArcGIS API for JavaScript v3 and chances are that it would be incompatible with a v5 if that were to ever exist.

Thoughts?

@tomwayson

**Comment by tomwayson** [comment]
That's an interesting question. My gut response is yes, keep the 4.

However, having been on the receiving end of the whole "it's just anuglar" fiasco, I can imagine a future where you'll regret having the 4 in there.

Renaming things is hard. I would think you'd want to avoid doing it again. I'd say drop the 4 too and just make it clear in the readme that it only supports v4. If someone really wants to write a component lib for v3, they can use angular-esri3-components.

**Comment by TheKeithStewart** [comment]
Changes that need to be made:
- [] rename repo to `angular-esri-components`
- [] publish angular-esri-components@1.0.0
- [] update links
  - [esri-loader](https://github.com/tomwayson/esri-loader/blob/master/README.md)
  - [jsapi-resources](https://github.com/Esri/jsapi-resources/tree/master/frameworks/angular)
  - [esri-angular-cli-example](https://github.com/tomwayson/esri-angular-cli-example/blob/master/README.md)
- [] update [esri-angular-cli-example](https://github.com/tomwayson/esri-angular-cli-example)
- [] update [ng-cli-electron-esri](https://github.com/TheKeithStewart/ng-cli-electron-esri)

**Comment by tomwayson** [comment]
Great work!

I'll add the update to jsapi-resources to my existing PR over there for angular-esri-loader.

**Comment by tomwayson** [comment]
FYI - https://github.com/Esri/jsapi-resources/pull/73/commits/bb4cd5f163484111e1275a87c4b4b468519fb48d
