### ISSUE TITLE
Cannot read property 'setTransform' of undefined error

### ISSUE THREAD

**Issue by kaden0428** [TheKeithStewart/angular-esri-components#15]
I program with angular-cli project. And I get the error message as title and code as below:
<pre>
import { Component, OnInit } from '@angular/core';
import { EsriLoaderService } from 'angular-esri-loader';
@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.css']
})
export class DemoComponent implements OnInit {
  webMapProperties: __esri.WebMapProperties = {
    basemap: "hybrid"
  };
  mapViewProperties: __esri.MapViewProperties = {
    zoom: 13,
    center: [121.5, 25]
  };
  map: __esri.Map;
  mapView: __esri.MapView;

  constructor(private esriLoader: EsriLoaderService) { }

  ngOnInit() {
  }

  onMapInit(mapInfo: { map: __esri.Map, mapView: __esri.MapView }) {
    this.map = mapInfo.map;
    this.mapView = mapInfo.mapView;
    this.esriLoader.loadModules([
      'esri/layers/FeatureLayer',
      'esri/renderers/SimpleRenderer',
      'esri/symbols/SimpleMarkerSymbol',
      'esri/Color',
      'esri/tasks/QueryTask',
      'esri/tasks/support/Query',
      'esri/geometry/SpatialReference',
      'esri/layers/GraphicsLayer',
      'esri/Graphic',
      'esri/geometry/Point',
      'esri/layers/Layer'
    ]).then(([FeatureLayer, SimpleMarkerSymbol, SimpleRenderer, Color,
      QueryTask, Query, SpatialReference, GraphicsLayer, Graphic,
      Point, Layer]:
      [__esri.FeatureLayerConstructor, __esri.SimpleMarkerSymbolConstructor,
        __esri.SimpleRendererConstructor, __esri.ColorConstructor,
        __esri.QueryTaskConstructor, __esri.QueryConstructor,
        __esri.SpatialReferenceConstructor, __esri.GraphicsLayerConstructor,
        __esri.GraphicConstructor, __esri.PointConstructor, __esri.Layer]) => {

      let sym = new SimpleMarkerSymbol({
        size: 10,
        color: new Color("#0000FF"),
        style: 'square',
        outline: {
          color: new Color("#FFFF00"),
          width: 3
        }
      });
 
      this.mapView.then(res => {
        let gc = new Graphic({
          geometry: new Point({ longitude: 121.54717481541498, latitude: 25.048117052172238 }),
          symbol: sym
        });
        this.mapView.graphics.add(gc);
      });

    })
  }
}

</pre>
I try to add a point graphic to the map.

**Comment by kaden0428** [comment]
The error image as below
![image](https://user-images.githubusercontent.com/15519443/27981017-c213885c-63b7-11e7-9fe0-d4f2e88f0029.png)

**Comment by TheKeithStewart** [comment]
Hi @kaden0428,

I see that you got this working with the angular-esri-loader at https://github.com/tomwayson/angular-esri-loader/issues/25.  Are you still having an issue with it here?

**Comment by kaden0428** [comment]
Thank you for your attention. I had solved problem since I had simplified the load modules as below:
I think all loaded modules and declared name should have the same order.
![image](https://user-images.githubusercontent.com/15519443/28022645-573da5cc-65be-11e7-8715-e94536ce54de.png)
