### ISSUE TITLE
How to add TileLayer and FeatureLayer?

### ISSUE THREAD

**Issue by sajeelmunir** [TheKeithStewart/angular-esri-components#17]
Hi there,

I want to load a Tile layer and Feature Layer map using this angular-esri-components? Please help!

My code like this:
let transportationLyr = new TileLayer({
      url: "https://MapServer" // My Map Server Address
    });
this.map.layers.add(transportationLyr);

I really appreciate any help you can provide.

**Comment by TheKeithStewart** [comment]
Take a look at https://github.com/TheKeithStewart/angular-esri-components/issues/12 for an example of how to add a feature layer. Adding a tile layer could be done similarly.

**Comment by TheKeithStewart** [comment]
This issue appears to be closed
