### ISSUE TITLE
Can't build with ng build --prod

### ISSUE THREAD

**Issue by rrdlpl** [TheKeithStewart/angular-esri-components#18]
I can't build my project that uses this library because this error. I reproduced in angular 4 and 2, angular-cli >= 1.0.0

ERROR in ng:///C:/Users/rdelaparral/workspace/site-builder-final/Seon.SiteBuilder.UI/node_modules/angular-esri-components/src/lib/widgets/layers-toggle/layers-toggle.component.d.ts.LayersT
oggleComponent.html (3,5): Property 'items' does not exist on type 'Collection'.

Please help :(

**Comment by V1ct0rV** [comment]
I have same problem, any thoughts?

**Comment by TheKeithStewart** [comment]
@rrdlpl @V1ct0rV,

Sorry for the slow response on this.  I've been out of commission for a little bit due to the flooding in Houston but I'm back online now and will take a look at this.

**Comment by TheKeithStewart** [comment]
@V1ct0rV, I just merged in a PR from @rrdlpl that I believe fixes this issue.  Please let me know if you continue to experience this and I will take another look.

Thanks again to both of you for bringing this up and sorry for my slow response.

**Comment by V1ct0rV** [comment]
Hi, Its working! Thanks
