### ISSUE TITLE
__esri.MapProperties.basemap problem

### ISSUE THREAD

**Issue by marksnorgate** [TheKeithStewart/angular-esri-components#20]
I am evaluating various mapping solutions for a project I'm working on, and the ArcGIS JS API is one I am investigating. We will be using v4.5 of the API.

I have run into an issue trying to replicate [this sandboxed sample from the ArcGIS site](https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=intro-mapview) in Angular using the `angular-esri-components` and `angular-esri-loader` as demoed in [this repository](https://github.com/tomwayson/esri-angular-cli-example).

The problem I am having is with the `__esri.MapProperties` type, which from the type information in `@types\arcgis-js-api` looks like this:

```
interface MapProperties extends LayersMixinProperties {
    allLayers?: CollectionProperties<LayerProperties>;
    basemap?: BasemapProperties;
    ground?: GroundProperties;
}
```
However, trying to replicate the sample in Angular, I have to set the `MapProperties` like this:
```
mapProperties: __esri.MapProperties = {
    basemap: "streets"
};
```
This fails, because it does not correspond to the shape of the interface: `basemap` needs to be a `BasemapProperties` which looks like this:
```
interface BasemapProperties extends LoadableProperties {
  baseLayers?: CollectionProperties<LayerProperties>;
  id?: string;
  loaded?: boolean;
  portalItem?: PortalItemProperties;
  referenceLayers?: CollectionProperties<LayerProperties>;
  thumbnailUrl?: string;
  title?: string;
}
```
In an effort to get the code up and running, I have implemented a temporary solution by modifying the type file so that `MapProperties` looks like this:
```
interface MapProperties extends LayersMixinProperties {
  allLayers?: CollectionProperties<LayerProperties>;
  basemap?: string; //BasemapProperties;
  ground?: GroundProperties;
}
```
When I do this, the app successfully displays the map in the browser and works as expected.

Clearly this is not a solution &mdash; can anyone tell me where I'm going wrong or if I'm missing something?

Thanks, Mark

**Comment by marksnorgate** [comment]
Having read through [the docs on the ArcGIS site](https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#basemap), I came across this:

> Specifies a basemap for the map. The basemap is a set of tile layers that give geographic context to the MapView or SceneView and the other operational layers in the map.
>
> This value can be an instance of Basemap or one of the strings listed in the table below.

Is this a shortcoming of the [type definition](https://www.npmjs.com/package/@types/arcgis-js-api)?

**Comment by marksnorgate** [comment]
Ok, another update.

I found [this post](https://github.com/Esri/jsapi-resources/issues/77) from which I contrived the following:
```
mapProperties: __esri.MapProperties = {
  basemap: __esri.Basemap.fromId('streets')
};
```
No TypeScript errors, Angular CLI/webpack compile without complaining, but in the browser I receive the following error:
> ERROR Error: Uncaught (in promise): ReferenceError: '__esri' is undefined

So, for the moment, I am using:
```
mapProperties: __esri.MapProperties = {
  basemap: 'streets' as any as __esri.Basemap
};
```
Suggestions on how I can fix the first method which seems a little less smelly?

**Comment by andygup** [comment]
@marksnorgate try updating to JS API v4.6. You shouldn't need to do `as any as __esri.` anymore.

**Comment by TheKeithStewart** [comment]
@marksnorgate Is this still an issue for you? Did updating the version of the JSAPI that you are using help?

Sorry for taking so long to reply. I'm trying to get this library back up to date now and should be much more responsive.

**Comment by TheKeithStewart** [comment]
Closing because I can't reproduce and because of inactivity on this issue.
