### ISSUE TITLE
Show popup or infobox on a map

### ISSUE THREAD

**Issue by z3dmax** [TheKeithStewart/angular-esri-components#22]
Hi,
is it possible to show a popup or window box or something similar using this library? Is there any example?
I've an Angular5  running project with everything right except popups.

```
 this.map.on('click', function($event) {
            // Here I need to show a popup of a clicked point using data stored into it's InfoTemplate
        });
```

Here original [InfoTemplate ](https://developers.arcgis.com/javascript/latest/sample-code/intro-popuptemplate/index.html)Esri example:

**Comment by TheKeithStewart** [comment]
@z3dmax I had forgotten about an example that I put together recently that shows putting a graphic on a map that includes a popup. Take a look at [this](https://github.com/TheKeithStewart/angular-esri-feature-layer-example/blob/master/src/app/app.component.ts).
