### ISSUE TITLE
How can I enable WebGL rendering?

### ISSUE THREAD

**Issue by shadab08** [TheKeithStewart/angular-esri-components#33]
The ArcGIS docs recommend using WebGL rendering rather than default SVG rendering for creating client-side Feature Layers.

https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#webgl-rendering

In order to do this, the docs say:

To enable WebGL rendering for FeatureLayers, paste the following script in your application prior to loading the ArcGIS API for JavaScript:

```
    <script>
      var dojoConfig = {
        has: {
          "esri-featurelayer-webgl": 1
        }
      };
    </script>
```

**Comment by tomwayson** [comment]
Have you tried doing just that? Place a script like that in your document's `<head>`?

**Comment by TheKeithStewart** [comment]
@shadab08 Did Tom's comment work for you?

**Comment by shadab08** [comment]
It is not working for me. Though I am not sure whether implementing Tom's suggestion had any impact or not. There are other limitation of WebGL which might be preventing it from working in my case as highlighted in below post.
https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#webgl-rendering

For now, we have dropped the idea of using highlight feature but instead we are playing around with Graphics.

Thanks for helping me out. I will closing this ticket.
