### ISSUE TITLE
Change esri css url to https

### ISSUE THREAD

**Issue by tonivrbic** [TheKeithStewart/angular-esri-components#35]
Inside the environments.ts file the **arcGisCssUrl** uses http:// instead of https:// or just ://. This causes, on sites using https, blocking of loading the stylesheet because it violates the mixed content policy.

**Comment by dLeung09** [comment]
This has caused issues for me as well

**Comment by rosostolato** [comment]
I resolved by myself and created a pull request. For now, I published a new package on npm while my PR is not approved:
https://www.npmjs.com/package/angular-esri-components-https
